import XCTest
@testable import meee2Kit

final class FullTranscriptReaderTests: XCTestCase {

    // MARK: - Helper: 把若干 jsonl 行写入临时文件，返回路径
    private func writeFixture(_ lines: [String]) -> String {
        let dir = NSTemporaryDirectory()
        let path = (dir as NSString).appendingPathComponent("fxt-\(UUID().uuidString).jsonl")
        let body = lines.joined(separator: "\n") + "\n"
        try? body.write(toFile: path, atomically: true, encoding: .utf8)
        return path
    }

    // MARK: - Regression: assistant 正文出现 <bash-input> 字面量不能丢
    //
    // 真实场景：Claude 自己写了一段总结说 "...含 `<bash-input>` 标志，丢..."。
    // 旧版 parseBlock 用 text.contains("<bash-input>") 把整条 entry 误丢，
    // 导致右侧 Message List 看不到，但终端和卡片还在 —— 三处源对不上。
    func testAssistantDiscussingBashInputLiteralIsKept() {
        let line = """
        {"type":"assistant","timestamp":"2026-04-25T19:58:32.697Z","uuid":"a44f7dbf","message":{"role":"assistant","content":[{"type":"text","text":"完美——含 `<bash-input>` 标志，丢；其余保留为 injected。"}]}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1, "assistant text containing literal <bash-input> must NOT be filtered")
        XCTAssertEqual(entries.first?.type, "assistant")
        XCTAssertEqual(entries.first?.blocks.count, 1)
        XCTAssertEqual(entries.first?.blocks.first?.type, "text")
        XCTAssertTrue((entries.first?.blocks.first?.text ?? "").contains("<bash-input>"))
    }

    // MARK: - 本地命令回显（!command）仍然被丢
    //
    // Claude CLI 写本地命令 echo 都是 type=user + content=string 且整段以 marker 开头。
    // 这条必须继续被过滤，否则 ! 命令的 stdin/stdout 会污染 Message List。
    func testLocalCommandEchoStillFiltered() {
        let line = """
        {"type":"user","timestamp":"2026-04-25T10:00:00Z","uuid":"u1","message":{"role":"user","content":"<bash-input>ls -la</bash-input>"}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 0, "real local-command echo (user/string starting with <bash-input>) must still be dropped")
    }

    func testLocalCommandCaveatStillFiltered() {
        let line = """
        {"type":"user","timestamp":"2026-04-25T10:00:00Z","uuid":"u2","message":{"role":"user","content":"<local-command-caveat>Caveat: messages were generated by user running local commands.</local-command-caveat>"}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 0, "<local-command-caveat> user message must still be dropped")
    }

    // MARK: - Stop hook 注入消息保留并标为 injected 类型
    func testStopHookInjectedMessageBecomesInjected() {
        let line = """
        {"type":"user","isMeta":true,"timestamp":"2026-04-25T10:00:00Z","uuid":"u3","message":{"role":"user","content":"Stop hook feedback:\\n💬 Operator sent you a message:\\n\\nhello"}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1)
        XCTAssertEqual(entries.first?.type, "injected", "isMeta=true user (Stop hook injection) should be relabeled 'injected'")
    }

    // MARK: - 边界：用户合法 prompt 里只是「提到」<bash-input> 不应误丢
    //
    // 当前修复用 hasPrefix——只要 marker 不在开头就放行。如果哪天 hasPrefix
    // 改回 contains 这条会失败。
    func testUserMessageMentioningBashInputMidwayIsKept() {
        let line = """
        {"type":"user","timestamp":"2026-04-25T10:00:00Z","uuid":"u4","message":{"role":"user","content":"my question is: what does <bash-input> mean in your transcript?"}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1, "user prompt mentioning <bash-input> mid-text must be kept")
        XCTAssertEqual(entries.first?.type, "user")
    }

    // MARK: - parseBlock 内的 text block 不再扫 marker
    //
    // 即使 user 用 array 形式塞 <bash-input>（理论上不会发生，30 天历史 0 条），
    // 也不应在 block 层面被过滤掉——过滤策略只在 parseLine 的 string 分支。
    // 这条记录我们当前的契约：array 形式的 user 内容总是被保留。
    func testArrayFormUserContentNeverFilteredByBlockParser() {
        let line = """
        {"type":"user","isMeta":true,"timestamp":"2026-04-25T10:00:00Z","uuid":"u5","message":{"role":"user","content":[{"type":"text","text":"<bash-input>ls</bash-input>"}]}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1, "array-form user content is preserved (never observed as local-command echo in real transcripts)")
    }

    // MARK: - 空 thinking block 仍然被丢（不是回归，固化既有行为）
    func testEmptyThinkingBlockYieldsNoEntry() {
        let line = """
        {"type":"assistant","timestamp":"2026-04-25T10:00:00Z","uuid":"a1","message":{"role":"assistant","content":[{"type":"thinking","thinking":"","signature":"sig"}]}}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 0, "empty thinking block produces no entry (no useful content to render)")
    }

    // MARK: - last-prompt schema：用户真实 prompt 必须被识别成 user entry
    //
    // 新版 Claude CLI 把用户原话写在 type=last-prompt 的 lastPrompt 字段里，
    // 普通 type=user 几乎只承载 tool_result。如果不识别 last-prompt，Web UI
    // 永远看不到用户说了什么——比 <bash-input> 误丢更严重的回归。
    func testLastPromptBecomesUserEntry() {
        let line = """
        {"type":"last-prompt","sessionId":"s1","lastPrompt":"帮我把这个 bug 修了"}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1, "last-prompt entries must surface as user entries")
        XCTAssertEqual(entries.first?.type, "user")
        XCTAssertEqual(entries.first?.blocks.count, 1)
        XCTAssertEqual(entries.first?.blocks.first?.type, "text")
        XCTAssertEqual(entries.first?.blocks.first?.text, "帮我把这个 bug 修了")
    }

    func testEmptyLastPromptIsDropped() {
        let line = """
        {"type":"last-prompt","sessionId":"s1","lastPrompt":""}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 0, "empty lastPrompt produces no entry (no useful content)")
    }

    // last-prompt 没有 timestamp，但 reader 不能因此 reject——它是没有 ts 的合法 entry
    func testLastPromptWithoutTimestamp() {
        let line = """
        {"type":"last-prompt","sessionId":"s1","lastPrompt":"hi"}
        """
        let entries = FullTranscriptReader.read(transcriptPath: writeFixture([line]))
        XCTAssertEqual(entries.count, 1)
        XCTAssertNil(entries.first?.timestamp, "last-prompt entries have no timestamp; UI must not sort by ts")
    }

    // MARK: - isLocalCommandEcho helper 单独测试边界
    func testIsLocalCommandEchoBoundaries() {
        XCTAssertTrue(FullTranscriptReader.isLocalCommandEcho("<bash-input>ls</bash-input>"))
        XCTAssertTrue(FullTranscriptReader.isLocalCommandEcho("<bash-stdout>foo</bash-stdout>"))
        XCTAssertTrue(FullTranscriptReader.isLocalCommandEcho("<local-command-caveat>note</local-command-caveat>"))
        XCTAssertFalse(FullTranscriptReader.isLocalCommandEcho(""))
        XCTAssertFalse(FullTranscriptReader.isLocalCommandEcho("hello world"))
        XCTAssertFalse(FullTranscriptReader.isLocalCommandEcho("see <bash-input> tag"),
                       "marker mid-string is NOT a local command echo")
        XCTAssertFalse(FullTranscriptReader.isLocalCommandEcho(" <bash-input>"),
                       "leading whitespace defeats hasPrefix; this is intentional — real CLI output starts at column 0")
    }
}
