// AUTOGENERATED by meee2-online/scripts/emit-planner-contract.mts — do not edit.
// Source of truth: meee2-online/src/planner-runtime/contract/{enums,proposal}.ts
// Re-emit: `pnpm contract:emit` from meee2-online/

import Foundation

enum PlannerContract {
    static let executionModes: Set<String> = ["auto", "human"]
    static let executorTypes: Set<String> = ["claude", "codex", "cursor", "openClaw", "devin", "human", "mock"]
    static let nodeStatuses: Set<String> = ["draft", "ready", "working", "blocked", "done"]
    static let nodeKinds: Set<String> = ["step", "session", "artifact", "subCanvas", "external"]
    static let changeKinds: Set<String> = ["addNode", "updateNode", "attachArtifact"]
    static let proposalStatuses: Set<String> = ["pending", "approved", "applied", "rejected"]
}
