#!/usr/bin/env bash
# Overwrite App/BuildInfo.swift with the git commit/branch/date baked in, so the
# dev "About Meee2" panel can show which build is running. App/BuildInfo.swift is
# committed with placeholder values (so a plain `swift build` / CI / fresh clone
# always compiles); this script replaces them with real values and is wired into
# `pnpm build:dev` and `build.sh`. Falls back to "unknown" outside a git checkout.
# NOTE: this leaves the committed file modified locally — that's expected, don't
# commit the regenerated values.
set -euo pipefail

cd "$(dirname "$0")/.."

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Mark a dirty working tree so a build off uncommitted changes is obvious.
# Ignore App/BuildInfo.swift itself (it's always "dirty" after a prior build).
if ! git diff --quiet -- ':!App/BuildInfo.swift' 2>/dev/null \
   || ! git diff --cached --quiet -- ':!App/BuildInfo.swift' 2>/dev/null; then
    GIT_COMMIT="${GIT_COMMIT}+dirty"
fi

OUT="App/BuildInfo.swift"
cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/gen-build-info.sh — values overwrite the committed
// placeholder. Do NOT commit the regenerated values. See the committed copy.
enum BuildInfo {
    static let gitCommit = "${GIT_COMMIT}"
    static let gitBranch = "${GIT_BRANCH}"
    static let buildDate = "${BUILD_DATE}"
}
EOF

echo "[gen-build-info] ${OUT}: ${GIT_COMMIT} (${GIT_BRANCH}) ${BUILD_DATE}"
