#!/usr/bin/env bash
# Generate App/BuildInfo.swift with the git commit/branch/date baked in, so the
# dev "About Meee2" panel can show which build is running. Mirrors the WebDist
# convention: gitignored, regenerated before every swift build (build:dev,
# build.sh, validate.sh all call this). Falls back to "unknown" outside a git
# checkout (e.g. a source tarball) so the build still compiles.
set -euo pipefail

cd "$(dirname "$0")/.."

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Mark a dirty working tree so a build off uncommitted changes is obvious.
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    GIT_COMMIT="${GIT_COMMIT}+dirty"
fi

OUT="App/BuildInfo.swift"
cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/gen-build-info.sh — DO NOT EDIT, DO NOT COMMIT.
// Gitignored & regenerated before every swift build (mirrors Board/WebDist).
enum BuildInfo {
    static let gitCommit = "${GIT_COMMIT}"
    static let gitBranch = "${GIT_BRANCH}"
    static let buildDate = "${BUILD_DATE}"
}
EOF

echo "[gen-build-info] ${OUT}: ${GIT_COMMIT} (${GIT_BRANCH}) ${BUILD_DATE}"
